### ISSUE TITLE
no authorization

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [haraldronge/groupmanager#2]
Hi,

sometimes I get the error message
```
Fehler: keine Berechtigung
```
in the pages containing the command 
```
~~groupmanager~~
```
I don't know where it comes from and at what time it comes up.
 
As workaround I've added the NOCACHE macro in these wiki pages, but I don't know if its sufficient.

Regards
Juergen

**Comment by haraldronge** [comment]
Dear Jürgen,
      
      I don't think this has got anything to do with the groupmanager as
      such.
      Especially because it only occurs occasionally this is very
      unlikely.
      
      NOCACHE should not help very much, though it is possible when
      switching to a user with lesser rights, that cached content would
      be displayed that should not be accessible.
      For example with indexmenu and the like.
      But that does not seem to be the issue here.
      
      Personally I have never come across this error, I can't replicate
      it. What else did you find out?
      
      -- 
        Met vriendelijke groet,
        
        Harald Ronge
         
        
        TurTur
        Innovation Transitions
        Pastelstraat 6 II, 1073 HS Amsterdam
        Telefoon: 06 52450978
        Email: harald@turtur.nl
        www.turtur.nl 
      
      
      
      On 14-01-15 10:16, Juergen-aus-Koeln wrote:
    
    
      Hi,
      sometimes I get the error message
        "Fehler: keine Berechtigung"
      I don't know where it comes from. As workaround I've added the
        NOCACHE macro in the wiki pages, but I don't know if its
        sufficient.
      Regards
        Juergen
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Juergen-aus-Koeln** [comment]
I'll write to you if the error occurs again, perhaps I'll find a regularity. At the moment it works for me.

Regards
Juergen

**Comment by Juergen-aus-Koeln** [comment]
Hi Harald,

after definition of some new roles and correlated groupmanager pages, nothing goes on these pages any more without admin permission. And I don't know how to solve it. So what can I do?

Best regards
Juergen
