### ISSUE TITLE
Warnings concerning header information and variables compatibility

### ISSUE THREAD

**Issue by Globulle** [haraldronge/groupmanager#7]
Since last dokuwiki update (Release 2017-02-19b "Frusterick Manners") I encounter a series of warnings from the groupmanager plugin:

> Warning: Declaration of syntax_plugin_groupmanager::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /(...)/lib/plugins/groupmanager/syntax.php on line 933
> 
> Warning: Declaration of syntax_plugin_groupmanager::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /(...)/lib/plugins/groupmanager/syntax.php on line 933
> 
> Warning: Cannot modify header information - headers already sent by (output started at /datas/vol2/w4a149033/var/www/wiki.meristeme.org/htdocs/lib/plugins/groupmanager/syntax.php:933) in /(...)/inc/actions.php on line 210
> 
> Warning: Cannot modify header information - headers already sent by (output started at /(...)/lib/plugins/groupmanager/syntax.php:933) in /(...)/lib/tpl/dokuwiki/main.php on line 12

Do you know where it comes from? (I use PHP 7.0)

**Comment by Mark-van-Dijk** [comment]
You can fix this by editing /lib/plugins/groupmanager/syntax.php as follows:
On line 141 change "&$handler" to "Doku_Handler $handler"
On line 174 change "&$renderer" to "Doku_Renderer $renderer"

The warnings should stop.

**Comment by haraldronge** [comment]
Hopefully fixed by merging. If anybody is interested in taking over this plugin, please mail me. I am no longer busy with Dokuwiki; this plugin is useful and it would be a shame if nobody would do something with it.

**Comment by haraldronge** [comment]
Thank you Mark, I hope this is fixed.
      
      Am 14.09.17 11:50, schrieb Mark van Dijk:
    
    
      You can fix this by editing
        /lib/plugins/groupmanager/syntax.php as follows:
        On line 141 change "&$handler" to "Doku_Handler $handler"
        On line 174 change "&$renderer" to "Doku_Renderer $renderer"
      The warnings should stop.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haraldronge/groupmanager","title":"haraldronge/groupmanager","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/haraldronge/groupmanager">"https://github.com/haraldronge/groupmanager"</a>}},"updates":
 {
"snippets":[{"icon":"PERSON","message":"@Mark-van-Dijk in #7: You can fix this by editing /lib/plugins/groupmanager/syntax.php as follows:\r\nOn line 141 change \"\u0026$handler\" to \"Doku_Handler $handler\"\r\nOn line 174 change \"\u0026$renderer\" to \"Doku_Renderer $renderer\"\r\n\r\nThe warnings should stop."}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/haraldronge/groupmanager/issues/7#issuecomment-329432575">"https://github.com/haraldronge/groupmanager/issues/7#issuecomment-329432575"</a>}}}
    
    
    
    -- 
      Met vriendelijke groet,
      
      Harald Ronge
       
      
      TurTur
      Innovation Transitions
      Pastelstraat 6 III, 1073 HS Amsterdam
      Telefoon: 06 52450978
      Email: harald@turtur.nl
      www.turtur.nl
